### ISSUE TITLE
timestamp.proto Not Found

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#10]
## Expected Behavior

`protoc` should be able to find imported protos.

Example:

```proto
import "google/protobuf/timestamp.proto";
```

## Actual Behavior

`protoc` is reporting these files are missing. I can't find these files in this repo.

Do we need instructions for importing these protos?

## Steps to Reproduce the Problem

Try to generate types for `google-cloudevents/proto/google/events/cloud/pubsub/v1/events.proto`

**Comment by jskeet** [comment]
Everything in google/protobuf should come with the protoc installation.

At some point I'll create a Travis build that validates everything.

**Comment by jskeet** [comment]
Closing this as `compile.sh` now shows how to generate the types.
