### ISSUE TITLE
JSON Schema Gen'd Examples are Empty

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#126]
## Expected Behavior

When running the json schema generator from master, there should be no changes in the generated files:

```sh
./scripts/gen.sh
```

## Actual Behavior

Running the generator creates `examples` fields that are empty (`[]`).

```
+  "examples": [],
```

This is introduced here: https://github.com/googleapis/google-cloudevents/pull/111

**Comment by michaelawyu** [comment]
A PR (#130) has been sent.

**Comment by grant** [comment]
> A PR (#130) has been sent.

Thanks. I added a comment, and we should be able to merge after it's resolved.

**Comment by grant** [comment]
This was fixed in #130.
