### ISSUE TITLE
Generation scripts fail on Windows

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloudevents#154]
## Expected Behavior

Running `./scripts/gen.sh` on Windows should regenerate everything appropriately

## Actual Behavior

The schema is regenerated with very different content, and then there's a 

## Steps to Reproduce the Problem

- Start a Windows VM
- Install Go, Node and bash (simplest option for the latter is to use the bash that comes with Git for Windows)
- Clone this repo
- Run `./scripts/gen.sh` from bash and wait for the errors

Error seen:

```text
Error: ENOENT: no such file or directory, open 'C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\readme-catalog/../../jsonschema/catalog.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\readme-catalog\index.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\users\\jonskeet\\GitHub\\googleapis\\google-cloudevents\\tools\\readme-catalog/../../jsonschema/catalog.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

... but some part of the script had earlier *deleted* `jsonschema/catalog.json`. I don't know why yet - I haven't tried to debug it.

**Comment by grant** [comment]
I need to fix the backslash Windows path separators in this script:

https://github.com/googleapis/google-cloudevents/blob/master/tools/readme-catalog/index.js

Let me know if there's urgency to get to this, or I'll eventually get to it. It shouldn't be blocking core generation.

**Comment by jskeet** [comment]
No urgency - it's fine.

**Comment by grant** [comment]
Added a PR, but I cannot reproduce the issue on a Windows CI runner. If you're able to do so, or use some other virtual device to triage this issue, please LMK.

**Comment by jskeet** [comment]
It's still failing for me, after generating a *lot* of output. (Huge numbers of messages of "No such package nor message in package".) Will dig into it further locally when I get the change - reassigning it to myself.

**Comment by jskeet** [comment]
https://github.com/chrusty/protoc-gen-jsonschema/issues/52 suggests we can ignore those "No such package nor message in package" messages. I'm still confused as to why I don't see them in the CI logs though.

**Comment by jskeet** [comment]
Next issue: the "postgen" step of `tools/proto2jsonschema/gen.sh` gives this error:

```text
Fixing paths in dir: C:\users\jonskeet\GitHub\googleapis\google-cloudevents\jsonschema
(node:40496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined
    at getCloudEventPackage (C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\proto2jsonschema\postgen.js:157:37)
    at C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\proto2jsonschema\postgen.js:45:25
    at Array.map (<anonymous>)
    at C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\proto2jsonschema\postgen.js:40:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Postgen: End
```

**Comment by jskeet** [comment]
Okay, I *think* I've fixed postgen.js by adding this as line 45:

```js
filePath = filePath.replace(/\\/g, '/');
```

Let's see what comes next...

**Comment by jskeet** [comment]
Hooray - with that change in place, the tool completes. It looks like the only change generated is that we've lost the understanding of `bytes` fields - they all just code out as plain `string` fields in the schema, rather than with the format and binaryEncoding metadata. Obviously we need to fix that before really declaring victory... it feels like that's a very odd difference to see, given that it's within the Go code and has nothing to do with paths :(

Need to leave this issue for now, but it does at least feel like we've made progress.

**Comment by jskeet** [comment]
Just running this on Linux, and I get the same "No such package nor message in package" messages there too, so it looks like that isn't Windows-specific. 

Likewise the removal of base64 formatting from bytes fields appears to happen on Linux too.

@grant do you know anything about the base64 side of things? Is that from an unreleased version of the Chrusty plugin or something like that? If you run the scripts locally, what do you see?

**Comment by grant** [comment]
@jskeet sorry for not seeing this.

I get a clean diff with the latest generation.

I'm not sure about the issue with `base64` you're seeing. There has been some changes there, and there are inconsistencies in general with the latest JSON Schema spec, and the JSON schema golang library the chrusty tool uses. 

The latest schema points gives some metadata base64. Maybe create a new issue?

**Comment by jskeet** [comment]
I'm pretty sure it was an issue (on two entirely different machines) with an old version of the plugin being used. I suggest we don't worry about it, but remember the symptoms in case it comes up again.
