### ISSUE TITLE
Change default branch from `master` to `main`

### ISSUE THREAD

**Issue by grayside** [googleapis/google-cloudevents#177]
## Expected Behavior

Use `main` as the default branch.

## Actual Behavior

Continuing to use `master` as the default branch.

**Comment by grant** [comment]
While I understand we want to use the name `main` as the default branch in general, there would be significant work to re-name the repo up and downstream. A plan to change the branch name would require some upstream changes and probably should be done at the same time as other repos in this org, using tooling if available.

I'm going to close this, but I'm free to have a discussion around this and can re-open the issue upon request.
