### ISSUE TITLE
Crate the trigger for Firebase Auth events

### ISSUE THREAD

**Issue by long1eu** [googleapis/google-cloudevents#184]
I also posted the issue here, but this being so new no one knows how to do it.

https://stackoverflow.com/questions/66618852/creating-eventarc-triggers-for-firebase-auth-events

**Comment by grant** [comment]
Hi there,
Eventarc only supports 2 kind of events, Pub/Sub and Cloud Audit Logs.

Firebase Auth events are not supported, at least for the native kind of events that you can see with Cloud Function triggers.

Audit Logs triggers may work for this, but I'm not sure. Try looking for the audit log in the Cloud Console activity view. The docs may also have some advice:

https://cloud.google.com/eventarc/docs/determining-filters-cal

Hope that helps.

**Comment by long1eu** [comment]
Then I don't understand. The blog post mentioned events from firestore and
such in the first paragraph. Also there is the proto specifications for
these events.

Cloud Audit doesn't work since it doesn't contain the UserRecord.

https://www.google.com/amp/s/cloudblog.withgoogle.com/products/serverless/build-event-driven-applications-in-cloud-run/amp/

**Comment by iennae** [comment]
@long1eu are you trying to do something with Firebase or Firestore?

**Comment by long1eu** [comment]
I need firebase auth events and firestore events.

**Comment by grant** [comment]
> Then I don't understand. The blog post mentioned events from firestore and such in the first paragraph. Also there is the proto specifications for these events. Cloud Audit doesn't work since it doesn't contain the UserRecord. https://www.google.com/amp/s/cloudblog.withgoogle.com/products/serverless/build-event-driven-applications-in-cloud-run/amp/

Thanks for linking the article.

In the bullet points, the blogpost talked about:
- Receive events from 60+ Google Cloud sources (via Cloud Audit logs).

I believe Firestore events are supported but not Firebase auth. Here's an example trigger command:

```
gcloud eventarc triggers create TRIGGER \
    --destination-run-service=DESTINATION_RUN_SERVICE \
    --destination-run-region=DESTINATION_RUN_REGION \
    --event-filters="type=google.cloud.audit.log.v1.written" \
    --event-filters="serviceName=firestore.googleapis.com" \
    --event-filters="methodName=METHOD_NAME" \
    --service-account=PROJECT_NUMBER-compute@developer.gserviceaccount.com
```

Where Firestore `METHOD_NAME` may be:

- `google.cloud.location.Locations.GetLocation`
- `google.cloud.location.Locations.ListLocations`
- `google.firestore.admin.v1.FirestoreAdmin.CreateIndex`
- `google.firestore.admin.v1.FirestoreAdmin.DeleteIndex`
- `google.firestore.admin.v1.FirestoreAdmin.ExportDocuments`
- `google.firestore.admin.v1.FirestoreAdmin.GetField`
- `google.firestore.admin.v1.FirestoreAdmin.GetIndex`
- `google.firestore.admin.v1.FirestoreAdmin.ImportDocuments`
- `google.firestore.admin.v1.FirestoreAdmin.ListFields`
- `google.firestore.admin.v1.FirestoreAdmin.ListIndexes`

For reference, all method names are here: https://github.com/googleapis/google-cloudevents/blob/master/json/audit/service_catalog.json

Additionally for reference, the general documentation for creating a trigger is here:

https://cloud.google.com/eventarc/docs/creating-triggers#cloud-audit-logs

---

Again, for Firebase Auth events, I do not believe those audit log events are provided. I don't see it mentioned in the blogpost.

We're working on adding more support for events in Eventarc in the future. LMK if there are other questions.

**Comment by grant** [comment]
Closing this issue, but please comment if you'd like it to be re-opened.

**Comment by nickmeinhold** [comment]
Thanks @grant!  I'm just hoping to clarify so I can stop trying to figure out what is and isn't possible - can I confirm that we can't currently use Eventarc to create Firestore triggers for document events? (ie. created, updated, deleted, written) The method names you posted and linked are all admin events and don't seem to include these document events.  If this is correct do you know where I can be paying attention to to know if this changes?  Thanks!

**Comment by jamesvnz** [comment]
@nickmeinhold it might be too late - but the docs indicate that audit events for document events are coming in a few days time (30th June): https://cloud.google.com/firestore/docs/audit-logging#upcoming-audit-logs

This will cover the Firestore events. There is no indication on what is happening with the Auth events.

**Comment by nickmeinhold** [comment]
Woohoo!  Thanks @jamesvnz!

**Comment by wonsuc** [comment]
> https://cloud.google.com/firestore/docs/audit-logging#upcoming-audit-logs

Is it released? I can't see those methods from the cloud console's event trigger list yet.

**Comment by jamesvnz** [comment]
> > https://cloud.google.com/firestore/docs/audit-logging#upcoming-audit-logs
> 
> Is it released? I can't see those methods from the cloud console's event trigger list yet.

Sigh, they've changed the docs: "Audit logs for the following operations will become available soon."

**Comment by jamesvnz** [comment]
For those interested, Data read and data write audit logging appears to be live now: https://cloud.google.com/firestore/docs/audit-logging#data-access-audit-logs:-data_read-and-data_write

**Comment by kylehotchkiss** [comment]
@jamesvnz have you gotten the read/write audit logs working in your projects? I tried to enable them in the Audit Logs settings under datastore/firestore API and view them in my project in the Log Explorer but seeing nothing yet. I tested some dummy read/writes both in the Firestore admin panel and via an application connected to firestore.

**Comment by jamesvnz** [comment]
Interesting - it's been rolled back. [change log](https://cloud.google.com/firestore/docs/release-notes#July_22_2021)  

> The DATA_READ and DATA_WRITE Data Access audit logs feature has been moved to a future release. It is not currently available.

And the documentation too: https://cloud.google.com/firestore/docs/audit-logging#upcoming-audit-logs

**Comment by wonsuc** [comment]
Is this available now?
