### ISSUE TITLE
Re-add cloudevents.proto in copybara

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#203]
## Expected Behavior

The `copybara` branch should keep the cloudevents.proto file:

https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloudevent.proto

## Actual Behavior

It's missing from the `copybara` branch.

**Comment by grant** [comment]
Jay has fixed the copybara config, so we should get a PR at some point.

**Comment by grant** [comment]
I think we need a proto change to trigger the copybara flow.

**Comment by jay-shi** [comment]
This issue is fixed in https://github.com/googleapis/google-cloudevents/commit/c4fac720212409589b6a0d3089650863172f728e
