### ISSUE TITLE
Alphabetize list of services in AUDIT_CATALOG.md

### ISSUE THREAD

**Issue by camiekim** [googleapis/google-cloudevents#225]
Pls alphabetize list of services. For example, "Cloud AutoML" is situated between "App Engine" and "BigQuery".  Other examples: Binary Authorization, Eventarc, Cloud Pub/Sub, Cloud Run, etc. Thanks.

**Comment by grant** [comment]
Currently the list of services is sorted by service name, not display name. So `automl.googleapis.com` is between GAE and BigQuery. Holding off for now. :)

**Comment by camiekim** [comment]
Looks like we can go ahead with the other repo instead. Thanks and I hope this didn't take too much of your time!

**Comment by grant** [comment]
ack, thanks!
