### ISSUE TITLE
Fix JSON Schema representation for `google.protobuf.Struct`

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#245]
The JSON schema conversion for proto fields that are `google.protobuf.Struct` produce incorrect schemas that have a "additionalProperties" field.

This whole key (`properties`) with `fields` should be removed from our JSON schemas. For example, this is causing issues with CAL payloads.

```
"properties": {
  "fields": {
    "additionalProperties": {
      "additionalProperties": true,
      "type": "object"
    },
    "type": "object",
    "description": "..."
  }
},
```

**Comment by averikitsch** [comment]
@grant can you add more context here or a proposed solution? Does the conversion process need to be updated? Then do the libraries need to be regenerated?

**Comment by grant** [comment]
Sure, here's some more context:

For some fields, our proto definitions are the type `google.protobuf.Struct`.

Example:

https://github.com/googleapis/google-cloudevents/blob/4e58ad34f45c0abd466e5b3a177a1a8d92b45dfe/proto/google/events/firebase/auth/v1/data.proto#L55

`google.protobuf.Struct custom_claims = 10;`

This currently produces a JSON schema that is more complicated than we need.

Actual:

```json
    "customClaims": {
      "properties": {
        "fields": {
          "additionalProperties": {
            "oneOf": [
              {
                "type": "array"
              },
              {
                "type": "boolean"
              },
              {
                "type": "number"
              },
              {
                "type": "object"
              },
              {
                "type": "string"
              }
            ]
          },
          "type": "object",
          "description": "Unordered map of dynamically typed values."
        }
      },
      "additionalProperties": true,
      "type": "object",
      "description": "User's custom claims, typically used to define user roles and propagated\n to an authenticated user's ID token."
    }
```

Expected:

```json
    "customClaims": {
      "type": "object",
      "description": "User's custom claims, typically used to define user roles and propagated\n to an authenticated user's ID token."
    }
```

https://github.com/googleapis/google-cloudevents/blob/master/jsonschema/google/events/firebase/auth/v1/AuthEventData.json#L92

We could simplify this to remove the `fields` property from struct types. I think this could be done by updating the protoc plugin for converting the `google.protobuf.Struct` type to an object by adding it as a well known type.

The process would be filing an issue similar to this one to add this well known type:
https://github.com/chrusty/protoc-gen-jsonschema/issues/63

**Comment by grant** [comment]
After updating the JSON schema in this repo, then re-generating the libraries would be the next step.

**Comment by grant** [comment]
I'm not currently working on this, so unassigning. Feel free to ping me :)

**Comment by grant** [comment]
Fixed with https://github.com/googleapis/google-cloudevents/pull/289
