### ISSUE TITLE
Add go_package to protos

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#27]
## Expected Behavior

All protos have a `go_package` option:

```proto
option go_package = "google.golang.org/genproto/googleapis/cloudevents/firebase/v1;firebase";
```

**Comment by jskeet** [comment]
This - and the other new issues are duplicates of #3, aren't they? I'd expect us to fix all these in a single PR, unless you think it's worth getting one language expert to create a PR for their language each time, which is definitely an option.

**Comment by grant** [comment]
Yes, it's a dup, sorry!
