### ISSUE TITLE
Add language option (e.g. go_package) for each proto

### ISSUE THREAD

**Issue by yolocs** [googleapis/google-cloudevents#3]
Ref: https://developers.google.com/protocol-buffers/docs/reference/go-generated#package
It will be used for generating go packages.

**Comment by jskeet** [comment]
Java options etc as well. We should probably work out everything needed for *one* proto, then apply it to all.

**Comment by grant** [comment]
We don't use protobufs for generating the Go or Java types as they depend on protobuf dependencies which are not required for events. We use JSON Schema instead.

https://github.com/googleapis/google-cloudevents-go

Java, Ruby, PHP, Node, Python, Go, .NET should be good in terms of language options, so I'll close this issue.
