### ISSUE TITLE
Cloud Firestore event is not being triggered.

### ISSUE THREAD

**Issue by wonsuc** [googleapis/google-cloudevents#336]
I'm using Cloud Run with Java server and made some Cloud Firestore Eventarc Triggers from console. 

`google.firestore.v1.Firestore.CreateDocument`  
`google.firestore.v1.Firestore.GetDocument`  

However, it's not working. I'm not sure what I'm missing.  

The Java server is just a simple "Hello World" Spring Boot project.  

I didn't configured [CloudEvents SDK](https://github.com/cloudevents/sdk-java) yet.  

I'm not sure because I didn't configured the SDK so the trigger is not working or if I'm missing something else.  

I'm not sure because I only tried to create Firestore document from Admin console so it is not working.  

I'm not sure because I made Cloud Run server for `Seoul(asia-northeast3)` so it's not working.   

I also found this [question](https://stackoverflow.com/q/68654256/4729203) from stackoverflow.  

I want to know if anybody is using it or succeed how to configure this properly.

**Comment by grayside** [comment]
Hello @wonsuc,

This event type is not yet available, to trigger on Firestore events please use an Audit Log.

The supported methods are listed in https://github.com/googleapis/google-cloudevents/blob/main/AUDIT_CATALOG.md#cloud-firestore, and the following tutorials show how use it:

* https://cloud.google.com/functions/docs/2nd-gen/getting-started#audit_logging
* https://cloud.google.com/eventarc/docs/run/cal

**Comment by grayside** [comment]
I also posted this answer to [Stackoverflow](https://stackoverflow.com/a/71576802/38408), feel free to continue the discussion there!

**Comment by nmazidi** [comment]
I'm also experiencing this. `google.firestore.v1.Firestore.CreateDocument` audit log events aren't being triggered at all.
