### ISSUE TITLE
Builds failing due to proto3 optional fields

### ISSUE THREAD

**Issue by muncus** [googleapis/google-cloudevents#405]
Builds recently began failing with a message about proto3 optional fields ([example](https://github.com/googleapis/google-cloudevents/actions/runs/3055934968/jobs/4929549173))

This was caused by the recent inclusion of this proto: https://github.com/googleapis/google-cloudevents/blob/main/proto/google/events/cloud/iot/v1/data.proto which uses the `optional` keyword in a proto3 file.

I'm investigating and working on a fix in #404 but since we rely on the google-cloudevents-dotnet repo for schema validation, changes will be needed there as well.

I believe this can be resolved by updating our versions of protoc and the protc-gen-jsonschema plugin, recent versions of both appear to properly support proto3 optional fields.

**Comment by jskeet** [comment]
@muncus: I'll fix up google-cloudevents-dotnet this morning.

**Comment by jskeet** [comment]
@muncus: google-cloudevents-dotnet should be fine now.
