### ISSUE TITLE
Display name for clouddeploy.googleapis.com should be "Cloud Deploy" and not "Cloud Deployment Manager"

### ISSUE THREAD

**Issue by camiekim** [googleapis/google-cloudevents#441]
This content is pulled into https://github.com/GoogleCloudPlatform/eventarc-samples/tree/main/eventarc-events/EventListGenerator and affects the public docs here: https://cloud.google.com/eventarc/docs/reference/supported-events#cloud-deployment-manager

**Comment by averikitsch** [comment]
cl/489269578

**Comment by averikitsch** [comment]
CL has been merged. @marcgovi can you push an update to the service_catalog.json?

**Comment by marcgovi** [comment]
Absolutely. The changes should be in once cl/490048292 is submitted.

**Comment by meteatamel** [comment]
Any update on this?

**Comment by meteatamel** [comment]
@marcgovi, thanks for the update. The event list will be auto-generated this Sunday and will be imported into docs afterwards.

**Comment by meteatamel** [comment]
Verified that the events list is now generated with "Cloud Deploy"
