### ISSUE TITLE
Can use google-cloudevents in C++ projects

### ISSUE THREAD

**Issue by DCMinds** [googleapis/google-cloudevents#489]
Hi Team,

We have two C++ applications. We are using protobuf messages to communicate between these applications.
we want a callback mechanism. i.e. we want to raise an event from one process which should get notified in another process.

Can we use google-cloudevents for this purpose?

**Comment by grayside** [comment]
Hi @DCMinds,

Thanks for your question. This repository is focused on providing type descriptions & definitions for events emitted from Google products.

It sounds like what you are looking for is support publishing your own events for HTTP delivery, if that's the case you might try filing a request with Eventarc or Pub/Sub in https://cloud.google.com/support/docs/issue-trackers for support in publishing a message in protobuf format.

Please reopen if I've misunderstood.
