### ISSUE TITLE
Add gogoproto.nullable extension for optional/nullable attributes

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#51]
## Expected Behavior

I'd expect that fields that are truly nullable produce libraries that allow these fields to be nullable.

For example, Pub/Sub `attributes` are nullable.

https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/pubsub/v1/data.proto#L38

---

Reading more into this, it appears there is a popular protobuf extension that allows nullable annotations.

```proto
bool   bol = 1 [(gogoproto.nullable) = false];
```

However, I'm not sure if we're going to be producing a client library for a language that uses this. It's worth mentioning in case we do need nullable attributes.

## Actual Behavior

Optional and required fields seem to be treated the same. This made all fields required when using TypeScript (we don't use proto definitions for this language anymore though).

**Comment by jskeet** [comment]
I'm not sure what you mean by "we do need nullable attributes".

I don't know about other languages, but in both C# and Java protobuf, map fields and repeated fields are never null - they just return empty results if they haven't been set. (This is generally handy, as it means you can iterate over the collection without having to check for nullity first.)

There's no distinction between "the map isn't present" and "the map is present but empty".

**Comment by grant** [comment]
This issue should be outdated/not needed with the new Go type generator.
