### ISSUE TITLE
StorageObjectData: type of metageneration and generation will be invalid

### ISSUE THREAD

**Issue by EkeMinusYou** [googleapis/google-cloudevents#522]
It looks like metageneration and generation type of `google.events.cloud.storage.v1.StorageObjectData` are invalid.

Shouldn't their actual type be string, not number?

I have attached the actual Event data received by the Cloud Function.

![image](https://github.com/googleapis/google-cloudevents/assets/41781157/22fbde44-c9ff-4ffc-baac-18cde2f8de37)

**Comment by EkeMinusYou** [comment]
That seems like it was my misunderstanding.

**Comment by jskeet** [comment]
@EkeMinusYou: Could you clarify the nature of your understanding? At first sight this does look like a problem. Was it actually something about how you're logging the CloudEvent content that was mistaken?

**Comment by EkeMinusYou** [comment]
Sorry for the confusion, but it looks like my initial concerns were correct after checking.

I'm using Golang in Cloud Function and I didn't get any error with code like below. 

```go
package function

import (
	"fmt"
	"context"

	"github.com/cloudevents/sdk-go/v2/event"
	"github.com/googleapis/google-cloudevents-go/cloud/storagedata"
	"google.golang.org/protobuf/encoding/protojson"
)

func init() {
	functions.CloudEvent("function", Do)
}

func Do(ctx context.Context, e event.Event) error {
	fmt.Printf("e: %s", string(e.Data()))
	var data storagedata.StorageObjectData
	if err := protojson.Unmarshal(e.Data(), &data); err != nil {
		return fmt.Errorf("protojson.Unmarshal: %w", err)
	}
        return nil
}
```

However, looking at the actual received value, it seems that `generation` was string.

**Comment by EkeMinusYou** [comment]
Thanks for the detailed explanation! understood.
