### ISSUE TITLE
Add "Name" column to README table

### ISSUE THREAD

**Issue by grayside** [googleapis/google-cloudevents#67]
## Expected Behavior

Add a `Source Name` or similar column to the README tab.

When focused on a use-case oriented onboarding to using CloudEvents without a sample, I'm looking for something which says "Audit Logs" or "Cloud Storage", not the existing identifiers.

## Actual Behavior

The machine readable names are useful for developers already oriented on the event types. There is no plain human-readable label.

**Comment by grant** [comment]
Thanks for the issue.

Are you expecting a Google product name per package? We could add that in the Package column.
Or are you asking for a name per CloudEvent type?

The table is already too wide for GitHub's default desktop markdown render. This table is also generated, so we would need to add that metadata to the proto comments likely.

**Comment by grayside** [comment]
I'm looking for an event type discovery experience which allows me to recognize the event types based on first looking for the product name. Group by vs. per row both work.

**Comment by grant** [comment]
See pending PR. ^
