### ISSUE TITLE
Remove Wrapper Type From JSON Schemas

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#72]
The JSON Schemas should probably not include the data wrapper type. This will allow this schema to be usable with editors that support JSON Schema, like VS Code. This shouldn't affect non-JSON-schema languages/generators.

For example, input the following in a JSON file in VS Code (specify the `$schema` field for autocompletion/IDE comments):

```json
{
  "$schema": "https://raw.githubusercontent.com/googleapis/google-cloudevents/master/proto/google/events/cloud/pubsub/v1/schema.json",
  "MessagePublishedEvent": {
    "message": {
      "data": "B%$JF",
      "messageId": "id",
      "attributes": {}
    }
  }
}
```

You'll notice nice autocompletion and inline documentation. I can imagine this could be useful to developers for testing. However, the schemas are currently stored with the wrapper type / multiple types in `schema.json`.

We should probably separate each data type with it's own schema rather than group them. Perhaps like:

- `google/events/cloud/pubsub/v1/jsonschemas/MessagePublishedData.json`

Where each type has a `jsonschemas/` folder with each [data message](https://github.com/googleapis/google-cloudevents#cloudevents-in-this-repository) schema. (Currently each product just has 1 type, but that is coincidental)

The expected behavior should be like:

```json
{
  "$schema": "https://raw.githubusercontent.com/googleapis/google-cloudevents/master/proto/google/events/cloud/pubsub/v1/jsonschemas/MessagePublishedEvent.json",
  "message": {
    "data": "B%$JF",
    "messageId": "id",
    "attributes": {}
  }
}
```

The wrapper types aren't useful for json schema users as far as I see, so they should be removed to achieve this behavior.

---

Related: https://github.com/googleapis/google-cloudevents/pull/69

What are your thought @michaelawyu @jskeet?
Existing generators can keep using the wrapped functionality (don't worry about modifying generators), but we can unwrap later.

**Comment by jskeet** [comment]
I don't know what best practice is for the schemas themselves, but I'd *expect* the result in terms of generated code to be the same as for protos, basically. One class per data type, and nested or not as per protos.
