### ISSUE TITLE
events.proto Doesn't Have All CE Attributes

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#73]
## Expected Behavior

I'd expect the events.proto files to have more than the CE TYPE. For example, other CE required fields

## Actual Behavior

The protos just have `google.events.cloud_event_type`.

https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/audit/v1/events.proto

**Comment by grant** [comment]
Any thoughts on this @jskeet? Even if we we're to comment other expected fields?

Might make the `events.proto` more understandable to folks like myself.

**Comment by jskeet** [comment]
I think we'd want to justify any additions - there are numerous ways we could do this, such as having a single common message for "attributes". I don't think we want to have a duplicate set of fields in every message.

@yolocs was really driving this side of things. At the moment, the messages do have a purpose in terms of correlating event type and data type, but I don't think we should add fields for the sake of it.

It *might* be worth adding fields for extension attributes, such as the Firebase auth/host ones we're considering. Again, those could be used to generate other code to help consume the CloudEvents.

**Comment by yolocs** [comment]
I'm all in to standardize other CE attributes.

**Comment by grant** [comment]
Going to close this for now. The `cloud_event_type` is really all what we need. Not sure if we want to put more info in the proto. Maybe a different place.
