### ISSUE TITLE
Use Git Tags For Marking Points in Time in Repo

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents#81]
## Expected Behavior

I expect to be able to reference to this SoT repo at a specific point in time for the repo.

Right now I have to use git SHAs, but **git tags** would be better. Should follow standard semver – commits that don't update/break the schema should be patch, non-breaking changes should be minor, otherwise breaking changes are major.

## Actual Behavior

I have to point to SHAs of the repo if I want to link to a specific schema at a point in time.

Major versions in the schemas are great, but gen'd clients should know at which specific version of this SoT the client was gen'd.

CC: @jskeet @grayside 
Relevant request: https://github.com/googleapis/google-cloudevents-nodejs/issues/51

Looking for @jskeet for thoughts here about this meta-versioning.

**Comment by jskeet** [comment]
Silly question: what does SoT stand for? I suspect I'll kick myself as soon as you say...

**Comment by jskeet** [comment]
I'm certainly happy to use tags for this. We need to design this fully though - I suspect an internal doc may be the right approach. In particular, I'd want to consider:

- What are the use cases for consuming these tags?
- Should the tags be product-specific, or repo-wide?
- Under what circumstances would we make any breaking changes?
- What triggers tagging - is it on every commit, or only when we know that a set of changes is stable?

**Comment by grant** [comment]
Good questions.
Right now and in the future I don't think we'll have bandwidth to create useful tags. They wouldn't be very useful for my use-cases. Closing for now.
